package model

import (
	"time"
)

type StockList struct {
	ID             int
	StockName      string
	StockId        string
	STOCKCHINANAME string
	CREATEDAT      time.Time
	UPDATEAT       time.Time
}
//`
//CREATE TABLE `stockLists` (
//  `ID` int(100) NOT NULL AUTO_INCREMENT,
//  `STOCKID` varchar(100) NOT NULL DEFAULT ' ',
//  `STOCKCHINANAME` varchar(100) DEFAULT NULL,
//  `STOCKNAME` varchar(100) DEFAULT NULL,
//  `STOCKUNIQUE` varchar(100) NOT NULL DEFAULT ' ',
//  `STOCKCON` varchar(100) NOT NULL DEFAULT ' ',
//  `STOCKCONSHORT` varchar(100) NOT NULL DEFAULT ' ',
//  `STOCKORG` varchar(100) NOT NULL DEFAULT ' ',
//  `UPDATEAT` datetime DEFAULT CURRENT_TIMESTAMP ,
//  PRIMARY KEY (`ID`) ,
//  UNIQUE KEY (`STOCKUNIQUE`)
//) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;`


//`CREATE TABLE `stockCollections` (
//  `ID` int(100) NOT NULL AUTO_INCREMENT,
//  `STOCKID` varchar(100) NOT NULL DEFAULT ' ',
//  `OPENATCASH` float NOT NULL DEFAULT '0',
//  `MIDCLOSEATCASH` float NOT NULL DEFAULT '0',
//  `MIDOPENATCASH` float NOT NULL DEFAULT '0',
//  `CLOSEATCASH` float NOT NULL DEFAULT '0',
//  `TRADECOUNT` decimal(18,2) NOT NULL DEFAULT '0.00',
//  `DATE` date NOT NULL DEFAULT '2000-01-01',
//  `STOCKUNIQUE` varchar(100) NOT NULL DEFAULT ' ',
//  `STOCKCOLLECTIONUNIQUE` varchar(100) NOT NULL DEFAULT ' ',
//  `UPDATEAT` datetime DEFAULT CURRENT_TIMESTAMP,
//  PRIMARY KEY (`ID`) ,
//  UNIQUE KEY (`STOCKCOLLECTIONUNIQUE`)
//) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
//`


//INSERT ignore INTO stockLists(STOCKID, STOCKCHINANAME, STOCKNAME, STOCKUNIQUE, STOCKCON, STOCKCONSHORT, STOCKORG) values('000001','上证指数','shzs','shStock000001','股票','Stock','sh')

//SELECT * FROM `stockCollections` s WHERE s.DATE BETWEEN '2015-01-01' AND '2016-01-01' AND s.STOCKUNIQUE = (SELECT STOCKUNIQUE FROM `stockLists` sl WHERE sl.STOCKID = '600123' AND sl.STOCKORG = 'sh' AND sl.STOCKCONSHORT = 'Stock')